name: CI

on:
  pull_request:
    branches:
      - add-more-ci-commands

jobs:
  build-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn

      - name: cache-yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress
            **/node_modules
          key: our-cache-yarn-${{ hashFiles('**/yarn.lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
        run: yarn install

  build-lint:
    needs: build-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          cache: yarn

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn

      - name: cache-yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress
            **/node_modules
          key: our-cache-yarn-${{ hashFiles('**/yarn.lock.json') }}

      - name: Lint
        run: yarn lint:ci

  build-test:
    needs: build-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          cache: yarn

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
          cache: yarn

      - name: cache-yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress
            **/node_modules
          key: our-cache-yarn-${{ hashFiles('**/yarn.lock.json') }}

      - name: Test
        run: yarn test:ci

  build-e2e:
    needs: build-dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          cache: yarn

      - name: Setup NodeJS 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: cache-yarn
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            /home/runner/.cache/Cypress
            **/node_modules
          key: our-cache-yarn-${{ hashFiles('**/yarn.lock.json') }}

      - name: e2e
        run: yarn e2e
